<Project>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <PropertyGroup>
    <Product>Cartograph</Product>
    <Authors>Angel Hernandez</Authors>
    <Company>Angel Hernandez</Company>
    <Copyright>Copyright (c) 2026 Angel Hernandez</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/angelhernandezm/Cartograph</PackageProjectUrl>
    <RepositoryUrl>https://github.com/angelhernandezm/Cartograph</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <Version>0.1.0-alpha</Version>
  </PropertyGroup>

</Project>
