<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <AssemblyName>cartograph-explorer-gtk</AssemblyName>
    <RootNamespace>Cartograph.Explorer.GtkApp</RootNamespace>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="GirCore.Gtk-4.0" Version="0.8.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cartograph.Explorer.Core\Cartograph.Explorer.Core.csproj" />
  </ItemGroup>

</Project>
